import { useState, useEffect } from 'react'
import { supabase } from '../lib/supabase'
import type { WeeklyReport as WeeklyReportType } from '../lib/supabase'
import { generateWeeklyReport } from '../lib/gemini'
import { TrendingUp, FileText, Send, Calendar, CheckCircle2 } from 'lucide-react'

const ReportSection = () => {
  const [report, setReport] = useState<WeeklyReportType | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState(false)

  useEffect(() => {
    fetchLatestReport()
  }, [])

  async function fetchLatestReport() {
    const { data } = await supabase
      .from('reports')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(1)
    
    if (data && data.length > 0) {
      setReport(data[0])
    }
  }

  async function handleGenerate() {
    setLoading(true)
    setError(null)
    setSuccess(false)

    try {
      // 데이터 수집
      const { data: assets } = await supabase.from('assets').select('*')
      const { data: news } = await supabase.from('news_cache').select('*').limit(5)

      if (!assets || assets.length === 0) {
        throw new Error('자산 데이터가 부족하여 리포트를 생성할 수 없습니다.')
      }

      const assetsSummary = assets.map(a => `- ${a.name}: ${a.amount.toLocaleString()}`).join('\n')
      const newsSummary = news?.map(n => `- [${n.importance}] ${n.title}`).join('\n') || '관련 뉴스 없음'

      const content = await generateWeeklyReport(assetsSummary, newsSummary)

      const { error: insertError } = await supabase.from('reports').insert([{
        start_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        end_date: new Date().toISOString().split('T')[0],
        content,
        ai_metadata: { asset_count: assets.length }
      }])

      if (insertError) throw insertError

      setSuccess(true)
      fetchLatestReport()
    } catch (err: any) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-3xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-1000">
      {/* Header Card */}
      <div className="glass p-8 rounded-[2rem] text-center border-t border-white/40">
        <div className="w-16 h-16 bg-primary/20 rounded-2xl flex items-center justify-center mx-auto mb-4">
          <TrendingUp className="text-primary w-8 h-8" />
        </div>
        <h2 className="text-2xl font-black mb-2 text-slate-900">주간 투자 전략 리포트</h2>
        <p className="text-slate-500 mb-6 font-medium">지난 한 주의 자산 흐름과 뉴스를 분석하여<br/>다음 주 자산 운용 관점을 제안합니다.</p>
        
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="relative group bg-primary hover:bg-blue-600 px-8 py-4 rounded-2xl font-black text-lg transition-all shadow-xl shadow-primary/30 disabled:opacity-50 overflow-hidden"
        >
          <div className="flex items-center gap-2 relative z-10">
            {loading ? <RefreshCw className="w-5 h-5 animate-spin" /> : <FileText className="w-5 h-5" />}
            {loading ? 'AI 분석 중...' : '신규 리포트 생성'}
          </div>
          <div className="absolute inset-0 bg-gradient-to-r from-white/0 via-white/10 to-white/0 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000" />
        </button>

        {success && (
          <div className="mt-4 flex items-center justify-center gap-2 text-secondary font-bold animate-bounce">
            <CheckCircle2 className="w-5 h-5" /> 리포트 생성 완료!
          </div>
        )}
        
        {error && <p className="mt-4 text-danger text-sm">{error}</p>}
      </div>

      {/* Report Content */}
      {report ? (
        <div className="glass p-8 md:p-12 rounded-[2rem] border border-black/5 relative shadow-sm">
          <div className="absolute top-8 right-8 flex items-center gap-2 text-slate-400 text-sm font-medium">
            <Calendar className="w-4 h-4" />
            {report.start_date} ~ {report.end_date}
          </div>
          
          <div className="prose prose-slate max-w-none">
            {/* Render markdown content */}
            <div className="whitespace-pre-wrap leading-relaxed text-slate-700 font-medium">
              {report.content}
            </div>
          </div>
          
          <div className="mt-12 pt-8 border-t border-black/5 flex justify-between items-center text-xs text-slate-400">
            <p>Generated by Gemini 3 Flash • 우상향 마이 자산라이프</p>
            <button className="flex items-center gap-1 hover:text-primary transition-colors font-bold">
              <Send className="w-3 h-3" /> 이메일로 알림 받기
            </button>
          </div>
        </div>
      ) : (
        !loading && (
          <div className="text-center py-20 text-slate-600 italic">
            생성된 리포트가 없습니다. 버튼을 눌러 첫 번째 분석을 시작하세요.
          </div>
        )
      )}
    </div>
  )
}

import { RefreshCw } from 'lucide-react'

export default ReportSection
